--------------------------------------------------------
--  File creato - venerdì-novembre-08-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Index BRAV_T_FUNZIONI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."BRAV_T_FUNZIONI_PK" ON "LDFDCADM"."BRAV_T_FUNZIONI" ("ID_FUNZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index BRAV_T_PERMESSI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."BRAV_T_PERMESSI_PK" ON "LDFDCADM"."BRAV_T_PERMESSI" ("ID_PERMESSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CERTIFICATI_TIPI_INVIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CERTIFICATI_TIPI_INVIO_PK" ON "LDFDCADM"."CERTIFICATI_TIPI_INVIO" ("ID_T_CERTIFICATO", "INVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CERTIFICATI_TIPI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CERTIFICATI_TIPI_PK" ON "LDFDCADM"."CERTIFICATI_TIPI" ("ID_T_CERTIFICATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_FDC_T_UTENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_FDC_T_UTENTI_PK" ON "LDFDCADM"."FDC_T_UTENTI" ("ID_TIPO_UTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_KEY_VALUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_KEY_VALUE_PK" ON "LDFDCADM"."CFG_KEY_VALUE" ("CFG_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_R_ANOMALIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_R_ANOMALIE_PK" ON "LDFDCADM"."CFG_R_FCITT_ANOMALIE" ("ID_FCITT_ANOMALIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_R_FCITT_COMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_R_FCITT_COMP_PK" ON "LDFDCADM"."CFG_R_FCITT_COMP" ("ID_CFG_R_FCITT_COMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_R_FCITT_NOTIFICHE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_R_FCITT_NOTIFICHE_PK" ON "LDFDCADM"."CFG_R_FCITT_NOTIFICHE" ("ID_FCITT_NOTIFICHE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_R_FCITT_SC_PERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_R_FCITT_SC_PERS_PK" ON "LDFDCADM"."CFG_R_FCITT_SCADENZE_PERSONALI" ("ID_SCADENZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_R_FCITT_WIDG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_R_FCITT_WIDG_PK" ON "LDFDCADM"."CFG_R_FCITT_WIDG" ("ID_CFG_R_FCITT_WIDG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_SERVIZI_ACCENTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_SERVIZI_ACCENTURE_PK" ON "LDFDCADM"."CFG_SRV_T_SERVIZI_ACCENTURE" ("ID_SERVIZIO_ACCENTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_SERVIZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_SERVIZI_PK" ON "LDFDCADM"."CFG_SRV_T_SERVIZI" ("ID_SERVIZIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_STATO_ATTIVITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_STATO_ATTIVITA_PK" ON "LDFDCADM"."CFG_SRV_T_STATO_ATTIVITA" ("ID_STATO_ATTIVITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_TIPO_ATTIVITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_TIPO_ATTIVITA_PK" ON "LDFDCADM"."CFG_SRV_T_TIPO_ATTIVITA" ("ID_TIPO_ATTIVITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_TIPO_CONTATTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_TIPO_CONTATTO_PK" ON "LDFDCADM"."CFG_SRV_T_TIPO_CONTATTO" ("ID_TIPO_CONTATTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_TIPO_DOCUMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_TIPO_DOCUMENTO_PK" ON "LDFDCADM"."CFG_SRV_T_TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_TIPO_PROPRIETA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_TIPO_PROPRIETA_PK" ON "LDFDCADM"."CFG_SRV_T_TIPO_PROPRIETA" ("ID_TIPO_PROPRIETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_SRV_T_TIPO_VEICOLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_SRV_T_TIPO_VEICOLO_PK" ON "LDFDCADM"."CFG_SRV_T_TIPO_VEICOLO" ("ID_TIPO_VEICOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_AVATAR_DEF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_AVATAR_DEF_PK" ON "LDFDCADM"."CFG_T_AVATAR_DEF" ("ID_AVATAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_AVATAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_AVATAR_PK" ON "LDFDCADM"."CFG_T_AVATAR" ("ID_AVATAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_COMP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_COMP_PK" ON "LDFDCADM"."CFG_T_CAT_COMP" ("ID_COMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_FUNZ_GLOBO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_FUNZ_GLOBO_PK" ON "LDFDCADM"."CFG_T_CAT_FUNZ_GLOBO" ("ID_FUNZ", "ID_GLOBO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_FUNZ_GLOBO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_FUNZ_GLOBO_UK1" ON "LDFDCADM"."CFG_T_CAT_FUNZ_GLOBO" ("ID_GLOBO", "ID_PROCEDIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_FUNZ_PAGINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_FUNZ_PAGINA_PK" ON "LDFDCADM"."CFG_T_CAT_FUNZ_PAGINE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_FUNZ_PAGINE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_FUNZ_PAGINE_UK1" ON "LDFDCADM"."CFG_T_CAT_FUNZ_PAGINE" ("CLASSE_PAGINA_STD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_FUNZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_FUNZ_PK" ON "LDFDCADM"."CFG_T_CAT_FUNZ" ("ID_FUNZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_FUNZ_SOSP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_FUNZ_SOSP_PK" ON "LDFDCADM"."CFG_T_CAT_FUNZ_SOSP" ("ID_FUNZ_SOSP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_GLOBO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_GLOBO_PK" ON "LDFDCADM"."CFG_T_CAT_GLOBO" ("ID_GLOBO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_LINK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_LINK_PK" ON "LDFDCADM"."CFG_T_CAT_FUNZ_LINK" ("ID_LINK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_RELATIVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_RELATIVES_PK" ON "LDFDCADM"."CFG_T_CAT_RELATIVES" ("ID_CAT_RELATIVES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_SEZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_SEZ_PK" ON "LDFDCADM"."CFG_T_CAT_SEZ" ("ID_SEZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_TIPI_NOTIFICHE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_TIPI_NOTIFICHE_PK" ON "LDFDCADM"."CFG_T_CAT_TIPI_NOTIFICHE" ("ID_T_NOTIFICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CAT_WIDG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CAT_WIDG_PK" ON "LDFDCADM"."CFG_T_CAT_WIDG" ("ID_WIDG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_CONTATTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_CONTATTI_PK" ON "LDFDCADM"."CFG_T_CONTATTI" ("ID_FCITT", "TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_EVENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_EVENTI_PK" ON "LDFDCADM"."CFG_T_EVENTI" ("ID_T_EVENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_FCITT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_FCITT_PK" ON "LDFDCADM"."CFG_T_FCITT" ("ID_FCITT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_FCITT_RELATIVES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_FCITT_RELATIVES_PK" ON "LDFDCADM"."CFG_T_FCITT_RELATIVES" ("ID_FCITT_RELATIVES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_NOTIFICHE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_NOTIFICHE_PK" ON "LDFDCADM"."CFG_T_NOTIFICHE" ("ID_NOTIFICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_PRSN_ID_IDX
--------------------------------------------------------

  CREATE INDEX "LDFDCADM"."CFG_T_PRSN_ID_IDX" ON "LDFDCADM"."CFG_T_FCITT" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_REL_ID_IDX
--------------------------------------------------------

  CREATE INDEX "LDFDCADM"."CFG_T_REL_ID_IDX" ON "LDFDCADM"."CFG_T_FCITT_RELATIVES" ("ID_FCITT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_REL_PAR_IDX
--------------------------------------------------------

  CREATE INDEX "LDFDCADM"."CFG_T_REL_PAR_IDX" ON "LDFDCADM"."CFG_T_FCITT_RELATIVES" ("ID_PERSON_PARENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_TESTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_TESTI_PK" ON "LDFDCADM"."CFG_T_TESTI" ("ID_CFG_TESTI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CFG_T_TIPI_ANOMALIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CFG_T_TIPI_ANOMALIE_PK" ON "LDFDCADM"."CFG_T_TIPI_ANOMALIE" ("ID_TIPO_ANOMALIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CPV_ANONIM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CPV_ANONIM_PK" ON "LDFDCADM"."CPV_ANONIM" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CPV_PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CPV_PERSON_PK" ON "LDFDCADM"."CPV_PERSON" ("PERSON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CPV_PERSON_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CPV_PERSON_UK1" ON "LDFDCADM"."CPV_PERSON" ("CODICE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index CZRM_T_SERVIZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."CZRM_T_SERVIZI_PK" ON "LDFDCADM"."CZRM_T_SERVIZI" ("ID_SERVIZIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index GEOWORKS_T_FUNZIONI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."GEOWORKS_T_FUNZIONI_PK" ON "LDFDCADM"."GEOWORKS_T_FUNZIONI" ("ID_FUNZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index GEOWORKS_T_SERVIZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."GEOWORKS_T_SERVIZI_PK" ON "LDFDCADM"."GEOWORKS_T_SERVIZI" ("ID_SERVIZIO", "ID_FUNZ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index ID_DELEGA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."ID_DELEGA_PK" ON "LDFDCADM"."CFG_T_CAT_FUNZ_DELEGHE" ("ID_DELEGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index ID_VEICOLO_DOCUMENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."ID_VEICOLO_DOCUMENTI_PK" ON "LDFDCADM"."SRV_T_VEICOLO_DOCUMENTI" ("ID_VEICOLO_DOCUMENTI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index JOB_INST_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."JOB_INST_UN" ON "LDFDCADM"."BATCH_JOB_INSTANCE" ("JOB_NAME", "JOB_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PL_T_DOCUMENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PL_T_DOCUMENTI_PK" ON "LDFDCADM"."PL_T_DOCUMENTI" ("CODICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PL_T_ISTANZE_DOCUMENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PL_T_ISTANZE_DOCUMENTI_PK" ON "LDFDCADM"."PL_T_ISTANZE_DOCUMENTI" ("CODICE_ISTANZA", "CODICE_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PL_T_ISTANZE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PL_T_ISTANZE_PK" ON "LDFDCADM"."PL_T_ISTANZE" ("CODICE_HERMES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PL_T_ISTANZE_SERIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PL_T_ISTANZE_SERIE_PK" ON "LDFDCADM"."PL_T_ISTANZE_SERIE" ("CODICE_ISTANZA", "CODICE_SERIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PL_T_SERIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PL_T_SERIE_PK" ON "LDFDCADM"."PL_T_SERIE" ("CODICE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PR_ANAGRAFICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PR_ANAGRAFICA_PK" ON "LDFDCADM"."PR_ANAGRAFICA" ("ID_ANAGRAFICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PR_PRESA_VISIONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PR_PRESA_VISIONE_PK" ON "LDFDCADM"."PR_PRIVACY_PRESA_VISIONE" ("ID_PRIVACY_VER", "ID_ANAGRAFICA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PR_PRIVACY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PR_PRIVACY_PK" ON "LDFDCADM"."PR_PRIVACY" ("ID_PRIVACY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PR_PRIVACY_VER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PR_PRIVACY_VER_PK" ON "LDFDCADM"."PR_PRIVACY_VER" ("ID_PRIVACY_VER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PR_SERVIZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PR_SERVIZI_PK" ON "LDFDCADM"."PR_SERVIZI" ("ID_SERVIZIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PR_SERVIZI_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PR_SERVIZI_UK1" ON "LDFDCADM"."PR_SERVIZI" ("COD_SERVIZIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PROVA_AUTODICHIARAZIONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PROVA_AUTODICHIARAZIONE_PK" ON "LDFDCADM"."PROVA_AUTODICHIARAZIONE" ("ID_AUTODICHIARAZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index PROVA_AUTODICHIARAZIONE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."PROVA_AUTODICHIARAZIONE_UK1" ON "LDFDCADM"."PROVA_AUTODICHIARAZIONE" ("ID_UTENTE", "CF_MINORE", "RELAZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index S3_CT46T_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."S3_CT46T_PK" ON "LDFDCADM"."S3_CT46T_COD_CATEGORIE" ("CT46_COD_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_ABILITAZIONI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_ABILITAZIONI_PK" ON "LDFDCADM"."SC_ABILITAZIONI" ("ID_ABILITAZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_ABILITAZIONI_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_ABILITAZIONI_UK1" ON "LDFDCADM"."SC_ABILITAZIONI" ("ID_OPERATORE", "ID_COMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_OPERATORI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_OPERATORI_PK" ON "LDFDCADM"."SC_OPERATORI" ("ID_OPERATORE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_OPERATORI_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_OPERATORI_UK1" ON "LDFDCADM"."SC_OPERATORI" ("OP_CF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_RUOLI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_RUOLI_PK" ON "LDFDCADM"."SC_RUOLI" ("ID_RUOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_SCADENZE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_SCADENZE_PK" ON "LDFDCADM"."SC_SCADENZE" ("ID_SCADENZA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SC_STATI_SCADENZE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SC_STATI_SCADENZE_PK" ON "LDFDCADM"."SC_STATI_SCADENZE" ("ID_STATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SPRING_SESSION_ATTRIBUTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SPRING_SESSION_ATTRIBUTES_PK" ON "LDFDCADM"."SPRING_SESSION_ATTRIBUTES" ("SESSION_PRIMARY_ID", "ATTRIBUTE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SPRING_SESSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SPRING_SESSION_PK" ON "LDFDCADM"."SPRING_SESSION" ("PRIMARY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_AUTODICHIARAZIONI_MINORI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_AUTODICHIARAZIONI_MINORI_PK" ON "LDFDCADM"."SRV_T_AUTODICHIARAZIONI_MINORI" ("ID_AUTODICHIARAZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_ATTIVITA_DOCUMENTI_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_ATTIVITA_DOCUMENTI_PK1" ON "LDFDCADM"."SRV_T_ATTIVITA_DOCUMENTI" ("ID_ATTIVITA_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_ATTIVITA_ESTERNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_ATTIVITA_ESTERNO_PK" ON "LDFDCADM"."SRV_T_ATTIVITA_ESTERNO" ("ID_ESTERNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_ATTIVITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_ATTIVITA_PK" ON "LDFDCADM"."SRV_T_ATTIVITA" ("ID_ATTIVITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_ATTIVITA_VEICOLI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_ATTIVITA_VEICOLI_PK" ON "LDFDCADM"."SRV_T_ATTIVITA_VEICOLI" ("ID_ATTIVITA_VEICOLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_AUDIT_SERVIZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_AUDIT_SERVIZI_PK" ON "LDFDCADM"."SRV_T_AUDIT_SERVIZI" ("ID_AUDIT_SERVIZIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_CONTATTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_CONTATTI_PK" ON "LDFDCADM"."SRV_T_CONTATTI" ("ID_CONTATTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_DOCUMENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_DOCUMENTI_PK" ON "LDFDCADM"."SRV_T_DOCUMENTI" ("ID_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_INDIRIZZI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_INDIRIZZI_PK" ON "LDFDCADM"."SRV_T_INDIRIZZI_OLD" ("ID_INDIRIZZO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_INDIRIZZI_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_INDIRIZZI_PK1" ON "LDFDCADM"."SRV_T_INDIRIZZI" ("ID_INDIRIZZO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_RELAZIONI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_RELAZIONI_PK" ON "LDFDCADM"."SRV_T_RELAZIONI" ("ID_RELAZIONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_SERVIZIO_BREADCRUMB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_SERVIZIO_BREADCRUMB_PK" ON "LDFDCADM"."SRV_T_SERVIZI_BREADCRUMB" ("ID_BREADCRUMB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_UTENTE_DOC_IDENTITA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_UTENTE_DOC_IDENTITA_PK" ON "LDFDCADM"."SRV_T_UTENTE_DOC_IDENTITA" ("ID_DOCUMENTO_IDENTITA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_UTENTE_IBAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_UTENTE_IBAN_PK" ON "LDFDCADM"."SRV_T_UTENTE_IBAN" ("ID_IBAN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_UTENTE_PATENTE_NUMERO_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_UTENTE_PATENTE_NUMERO_UK" ON "LDFDCADM"."SRV_T_UTENTE_PATENTE" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_UTENTE_PATENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_UTENTE_PATENTE_PK" ON "LDFDCADM"."SRV_T_UTENTE_PATENTE" ("ID_PATENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_UTENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_UTENTE_PK" ON "LDFDCADM"."SRV_T_UTENTI" ("ID_UTENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_UTENTE_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_UTENTE_UK" ON "LDFDCADM"."SRV_T_UTENTI" ("CODICE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_VEICOLI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_VEICOLI_PK" ON "LDFDCADM"."SRV_T_VEICOLI" ("ID_VEICOLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SRV_T_VEICOLI_TARGA_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SRV_T_VEICOLI_TARGA_UK" ON "LDFDCADM"."SRV_T_VEICOLI" ("TARGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0089848
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SYS_C0089848" ON "LDFDCADM"."HTE_SRV_T_UTENTI" ("RN_") ;
--------------------------------------------------------
--  DDL for Index SYS_C0091700
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SYS_C0091700" ON "LDFDCADM"."BATCH_JOB_INSTANCE" ("JOB_INSTANCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0091705
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SYS_C0091705" ON "LDFDCADM"."BATCH_JOB_EXECUTION" ("JOB_EXECUTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0091717
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SYS_C0091717" ON "LDFDCADM"."BATCH_STEP_EXECUTION" ("STEP_EXECUTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0091721
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SYS_C0091721" ON "LDFDCADM"."BATCH_STEP_EXECUTION_CONTEXT" ("STEP_EXECUTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0091725
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."SYS_C0091725" ON "LDFDCADM"."BATCH_JOB_EXECUTION_CONTEXT" ("JOB_EXECUTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index TABLE2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."TABLE2_PK" ON "LDFDCADM"."CZRM_T_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index TR_CLIENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."TR_CLIENTI_PK" ON "LDFDCADM"."TR_CLIENTI" ("NUMERO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index TR_CONTRATTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."TR_CONTRATTI_PK" ON "LDFDCADM"."TR_CONTRATTI" ("NUM_CONTRATTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index TR_DOMANDE_INDEX1
--------------------------------------------------------

  CREATE INDEX "LDFDCADM"."TR_DOMANDE_INDEX1" ON "LDFDCADM"."TR_DOMANDE" ("CF_RICHIEDENTE", "ID_STATO_DOMANDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
--------------------------------------------------------
--  DDL for Index TR_DOMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LDFDCADM"."TR_DOMANDE_PK" ON "LDFDCADM"."TR_DOMANDE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FDC_COMGE" ;
