--------------------------------------------------------
--  File creato - venerdì-novembre-08-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence BATCH_JOB_EXECUTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."BATCH_JOB_EXECUTION_SEQ"  MINVALUE 0 MAXVALUE 9223372036854775807 INCREMENT BY 1 START WITH 1320 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BATCH_JOB_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."BATCH_JOB_SEQ"  MINVALUE 0 MAXVALUE 9223372036854775807 INCREMENT BY 1 START WITH 1200 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BATCH_STEP_EXECUTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."BATCH_STEP_EXECUTION_SEQ"  MINVALUE 0 MAXVALUE 9223372036854775807 INCREMENT BY 1 START WITH 1260 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_R_FCITT_ANOMALIE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_R_FCITT_ANOMALIE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_R_FCITT_ANOMALIE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_R_FCITT_ANOMALIE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_R_FCITT_COMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_R_FCITT_COMP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1557 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_R_FCITT_COMP_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_R_FCITT_COMP_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_R_FCITT_NOTIFICHE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_R_FCITT_NOTIFICHE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 2167 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_R_FCITT_NOTIFICHE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_R_FCITT_NOTIFICHE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_R_FCITT_SCADENZE_PERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_R_FCITT_SCADENZE_PERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 6394 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_R_FCITT_SCADENZE_PERS_SEQ" TO "LDPERS";
  GRANT SELECT ON "LDFDCADM"."CFG_R_FCITT_SCADENZE_PERS_SEQ" TO "LDPERS";
  GRANT SELECT ON "LDFDCADM"."CFG_R_FCITT_SCADENZE_PERS_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_R_FCITT_WIDG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_R_FCITT_WIDG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 472 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_R_FCITT_WIDG_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_R_FCITT_WIDG_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_SERVIZI_ACCENTURE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_SERVIZI_ACCENTURE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 561 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_SERVIZI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_SERVIZI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_STATO_ATTIVITA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_STATO_ATTIVITA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_TIPO_ATTIVITA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_TIPO_ATTIVITA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_TIPO_CONTATTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_TIPO_CONTATTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_TIPO_DOCUMENTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_TIPO_DOCUMENTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_TIPO_PROPRIETA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_TIPO_PROPRIETA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_SRV_T_TIPO_VEICOLO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_SRV_T_TIPO_VEICOLO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_T_AVATAR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_AVATAR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "LDFDCADM"."CFG_T_AVATAR_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_COMP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_COMP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 15 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_COMP_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_COMP_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_FUNZ_PAGINE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_FUNZ_PAGINE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 427 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_FUNZ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_FUNZ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_FUNZ_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_FUNZ_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_FUNZ_SOSP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_FUNZ_SOSP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_FUNZ_SOSP_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_FUNZ_SOSP_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_RELATIVES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_RELATIVES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_RELATIVES_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_RELATIVES_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_SEZ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_SEZ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_SEZ_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_SEZ_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_TIPI_NOTIFICHE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_TIPI_NOTIFICHE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_TIPI_NOTIFICHE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_TIPI_NOTIFICHE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_CAT_WIDG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_CAT_WIDG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_CAT_WIDG_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_CAT_WIDG_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_EVENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_EVENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_EVENTI_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_EVENTI_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_FCITT_RELATIVES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_FCITT_RELATIVES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 446 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_FCITT_RELATIVES_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_FCITT_RELATIVES_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_FCITT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_FCITT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1543 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_FCITT_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_FCITT_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_NOTIFICHE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_NOTIFICHE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_NOTIFICHE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_NOTIFICHE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CFG_T_TIPI_ANOMALIE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CFG_T_TIPI_ANOMALIE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CFG_T_TIPI_ANOMALIE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."CFG_T_TIPI_ANOMALIE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence CPV_PERSON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."CPV_PERSON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 2107 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."CPV_PERSON_SEQ" TO "LDPERS";
  GRANT SELECT ON "LDFDCADM"."CPV_PERSON_SEQ" TO "LDPERS";
--------------------------------------------------------
--  DDL for Sequence FDC_PROTOCOLLO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."FDC_PROTOCOLLO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 67 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "LDFDCADM"."FDC_PROTOCOLLO_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence PACINO_PARPI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."PACINO_PARPI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PR_ANAGRAFICA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."PR_ANAGRAFICA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "LDFDCADM"."PR_ANAGRAFICA_SEQ" TO "LDPRIV";
  GRANT ALTER ON "LDFDCADM"."PR_ANAGRAFICA_SEQ" TO "LDPRIV";
--------------------------------------------------------
--  DDL for Sequence PR_PRIVACY_PRESA_VISIONE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."PR_PRIVACY_PRESA_VISIONE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."PR_PRIVACY_PRESA_VISIONE_SEQ" TO "LDPRIV";
  GRANT SELECT ON "LDFDCADM"."PR_PRIVACY_PRESA_VISIONE_SEQ" TO "LDPRIV";
--------------------------------------------------------
--  DDL for Sequence PR_PRIVACY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."PR_PRIVACY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."PR_PRIVACY_SEQ" TO "LDPRIV";
  GRANT SELECT ON "LDFDCADM"."PR_PRIVACY_SEQ" TO "LDPRIV";
--------------------------------------------------------
--  DDL for Sequence PR_PRIVACY_VER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."PR_PRIVACY_VER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."PR_PRIVACY_VER_SEQ" TO "LDPRIV";
  GRANT SELECT ON "LDFDCADM"."PR_PRIVACY_VER_SEQ" TO "LDPRIV";
--------------------------------------------------------
--  DDL for Sequence PR_SERVIZI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."PR_SERVIZI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."PR_SERVIZI_SEQ" TO "LDPRIV";
  GRANT SELECT ON "LDFDCADM"."PR_SERVIZI_SEQ" TO "LDPRIV";
--------------------------------------------------------
--  DDL for Sequence SC_ABILITAZIONI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SC_ABILITAZIONI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."SC_ABILITAZIONI_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."SC_ABILITAZIONI_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence SC_OPERATORI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SC_OPERATORI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."SC_OPERATORI_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."SC_OPERATORI_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence SC_SCADENZE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SC_SCADENZE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."SC_SCADENZE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."SC_SCADENZE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence SC_STATI_SCADENZE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SC_STATI_SCADENZE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT ALTER ON "LDFDCADM"."SC_STATI_SCADENZE_SEQ" TO "LDFDC";
  GRANT SELECT ON "LDFDCADM"."SC_STATI_SCADENZE_SEQ" TO "LDFDC";
--------------------------------------------------------
--  DDL for Sequence SRV_T_ATTIVITA_DOCUMENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_ATTIVITA_DOCUMENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_ATTIVITA_ESTERNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_ATTIVITA_ESTERNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_ATTIVITA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_ATTIVITA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1207 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_ATTIVITA_VEICOLI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_ATTIVITA_VEICOLI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_AUDIT_SERVIZI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_AUDIT_SERVIZI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1581 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_AUTODICHIARAZIONI_MINORI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_AUTODICHIARAZIONI_MINORI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_CONTATTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_CONTATTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 381 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_DOCUMENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_DOCUMENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_INDIRIZZI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_INDIRIZZI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_INDIRIZZI_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_INDIRIZZI_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_INDIRIZZI_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_INDIRIZZI_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_SERVIZIO_BREADCRUMB_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_SERVIZIO_BREADCRUMB_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_UTENTE_DOC_IDENTITA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_UTENTE_DOC_IDENTITA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_UTENTE_IBAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_UTENTE_IBAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_UTENTE_PATENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_UTENTE_PATENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_UTENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_UTENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 473 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_VEICOLI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_VEICOLI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_VEICOLO_DOCUMENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_VEICOLO_DOCUMENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SRV_T_VEICOLO_DOCUMENTI_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."SRV_T_VEICOLO_DOCUMENTI_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TABLE2_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LDFDCADM"."TABLE2_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
