@FdCPackagePropertiesAnnotation
package it.liguriadigitale.ponmetro.portale.presentation.pages.domandetrascrizionematrimoni;

import it.liguriadigitale.ponmetro.portale.presentation.common.FdCPackagePropertiesAnnotation;
