@FdCPackagePropertiesAnnotation
package it.liguriadigitale.ponmetro.portale.presentation.pages.domandetrascrizionematrimoni.richiesta;

import it.liguriadigitale.ponmetro.portale.presentation.common.FdCPackagePropertiesAnnotation;
